/* DO NOT EDIT THIS FILE - it is machine generated */
#include <jni.h>
/* Header for class com_example_specter_mishagram_NativeEncryption */

#ifndef _Included_com_example_specter_mishagram_NativeEncryption
#define _Included_com_example_specter_mishagram_NativeEncryption
#ifdef __cplusplus
extern "C" {
#endif
/*
 * Class:     com_example_specter_mishagram_NativeEncryption
 * Method:    cryption
 * Signature: (Ljava/lang/String;)Ljava/lang/String;
 */
JNIEXPORT jstring JNICALL Java_com_example_specter_mishagram_NativeEncryption_cryption
  (JNIEnv *, jobject, jstring);

#ifdef __cplusplus
}
#endif
#endif
